font:
    normal:
        family: SauceCodePro Nerd Font Mono
        style: Medium

    bold:
        family: SauceCodePro Nerd Font Mono
        style: Bold

    italic:
        family: SauceCodePro Nerd Font Mono
        style: Italic

    bold_italic:
        family: SauceCodePro Nerd Font Mono
        style: Bold Italic

    size: 18.0

shell:
    program: /opt/homebrew/bin/tmux
    # args:
    #     - attach

working_directory: /Users/mdvis/Code

env:
    TERM: xterm-256color

import:
    - gruvbox.yml