# zsh config

# sys {
    #export LANG=en_US.UTF-8
    export PATH=/opt/homebrew/bin:$PATH
    export PATH="${HOME}/.local/bin":$PATH
    export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
    export PATH="${HOME}/go/bin:$PATH"
# }

# fzf {
    export FZF_DEFAULT_COMMAND="fd -H -t f -t d --exclude={.git,.idea,.vscode,.sass-cache,node_modules,build}"
    export FZF_DEFAULT_OPTS="--height 40% --border --preview '(highlight -O ansi {} || cat {}) 2> /dev/null | head -50'"
# end fzf }

# zsh {
    export ZSH=$HOME/.oh-my-zsh
    export UPDATE_ZSH_DAYS=26
    export ZSH_THEME="avit"

    source $ZSH/oh-my-zsh.sh
    [ -f ~/.alias ] && source ~/.alias
# }

# nvm {
    export NVM_DIR="$HOME/.nvm"
    export NVM_NODEJS_ORG_MIRROR=https://npm.taobao.org/mirrors/node/

    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

    # place this after nvm initialization!
    autoload -U add-zsh-hook
    load-nvmrc() {
      local node_version="$(nvm version)"
      local nvmrc_path="$(nvm_find_nvmrc)"

      if [ -n "$nvmrc_path" ]; then
        local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

        if [ "$nvmrc_node_version" = "N/A" ]; then
          nvm install
        elif [ "$nvmrc_node_version" != "$node_version" ]; then
          nvm use
        fi
      elif [ "$node_version" != "$(nvm version default)" ]; then
        echo "Reverting to nvm default version"
        nvm use default
      fi
    }
    add-zsh-hook chpwd load-nvmrc
    load-nvmrc
# }

# gvm {
    source /Users/mdvis/.gvm/scripts/gvm
# }

plugins=(git brew gulp man npm macos tmux python sudo yarn)

eval $(thefuck --alias)
