import = ["gruvbox.yml"]
working_directory = "/Users/mdvis/Code"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Medium"

[shell]
program = "/Users/mdvis/.local/bin/tmux"
